<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\perry\Documents\3D\Spaceship\static\models\star_wars_battlefront_-_tie_bomber.glb --root /models/ --printwidth 120 --precision 2
Author: Neut2000 (https://sketchfab.com/Neut2000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-battlefront-tie-bomber-7a30f362f6fb4ee8853ba2321927d2c5
Title: Star Wars Battlefront - TIE Bomber
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/star_wars_battlefront_-_tie_bomber.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials['Shape.095']} />
      <T.Mesh geometry={gltf.nodes.Object_3.geometry} material={gltf.materials['Shape.096']} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
