<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\perry\Documents\3D\Spaceship\static\models\star_wars_millennium_falcon.glb --root /models/ --printwidth 120 --precision 2
Author: Franko (https://sketchfab.com/franko89)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-millennium-falcon-a480073ca161430c911dc1a29427c22c
Title: Star Wars Millennium Falcon
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/models/star_wars_millennium_falcon.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 19, -120]}>
      <T.Mesh geometry={gltf.nodes.Object_2.geometry} material={gltf.materials.millennium} />
      <T.Mesh geometry={gltf.nodes.Object_3.geometry} material={gltf.materials.millennium} />
      <T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials.millennium} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
